# Marker Set Options
# Documentation: https://bluemap.bluecolored.de/wiki/customization/Markers.html#marker-sets
MarkerSetName: "Signs"
Toggleable: true
DefaultHidden: false

# Allows you to limit the distance to the camera at which the sign markers are shown.
# If it's 0, the markers will always be visible, even when zoomed out really far.
MaxDistance: 32

# If you have a world with many old or incompatible chunks, the extraction process
#  may be giving off many warnings about it.
# You can set this to true to suppress those warnings.
# Keep in mind that this will still not make the signs from those chunks actually show up,
#  it will only hide the warnings about these broken chunks.
SuppressWarnings: false

# Only mark signs with text
IgnoreBlankSigns: false