name: BlueMapSignExtractor
version: '${project.version}'
main: com.technicjelle.bluemapsignextractor.impl.paper.BlueMapSignExtractor
api-version: '1.13'
depend:
  - BlueMap
authors:
  - TechnicJelle
url: '${project.url}'
description: '${project.description}'
